### ISSUE TITLE
Corrección en Heart-baud.ice

### ISSUE THREAD

**Issue by SpasNH** [FPGAwars/Collection-Jedi#2]
Hola Obijuan! :)
Encontré algo que se podría corregir en Collection-Jedi-1.9.0 / blocks / Varios / Bombeo / Tics /Heart-baud.ice. En la segunda linea:
`define B115200 104  //-- 103 for TX, 104 for RX
Tal y como indicas en el comentario debe ser 103. Afecta a: Collection-Jedi-1.9.0 / blocks / Varios / Serial / blocks /Serial-tx.ice  por estar construido con ese corazón. Al enlazar un rx directamente con un tx, y al enviar desde ScriptCommunicator "0123456789" devuelve "012468", a veces "013579'.
Saludos

**Comment by Obijuan** [comment]
Gracias! Corregido en el repo! :-)
