### ISSUE TITLE
Bloque Rx y Tx Blackice MX

### ISSUE THREAD

**Issue by Tyson1414** [FPGAwars/Collection-Jedi#8]
quería comentar que el bloque Rx y Tx no me sirvieron con la Blackice MX recibe información pero no son los datos esperados.

**Comment by Tyson1414** [comment]
ya resolví el problema, los bloques de la colección están diseñados para una frecuencia de 12MHz y la Blackice MX tiene un reloj de 25MHz

**Comment by Obijuan** [comment]
En la colección stdio puedes encontrar componentes del puerto serie con un parámetro adicional de entrada para usarlos con placas con diferentes frecuencias de reloj:
https://github.com/FPGAwars/Collection-stdio

En cuanto pueda haré un cuaderno técnico sobre esto, porque todavía no está documentado

También encontrarás ayuda de otros usuarios en la lista de FPGAwars:
https://groups.google.com/g/fpga-wars-explorando-el-lado-libre

**Comment by Tyson1414** [comment]
Muchas gracias por responder, solo una cosa pequeña, ya había encontrado ese grupo de google pero siempre que intento ingresar me aparece que el contenido no está disponible, igual me pasa con el link que pusiste, parece que el contenido esta privado o se necesita de algún permiso.

**Comment by Obijuan** [comment]
El grupo de google debería ser visible para todo el mundo. Por favor, confírmame si puedes ver información al acceder aquí: 

https://groups.google.com/forum/#!forum/fpga-wars-explorando-el-lado-libre

Si no puedes ver nada es que ha ocurrido algún problema (y lo intentaré solucionar)

Gracias

**Comment by Tyson1414** [comment]
ya vi cual era el problema, el dominio de mi universidad no me deja ingresar a los grupos de google pero desde mi cuenta personal si puedo ingresar, gracias de nuevo por responder
